/**
 * Codegen del prompt del consulente. Legge `prompts/consulente.md`
 * (unico originale versionato) e scrive `src/consulente-prompt.generated.ts`
 * con:
 *
 *   export const PROMPT_MARKDOWN = "…";     // contenuto letterale
 *   export const PROMPT_VERSION  = "…";     // sha256[:8] del contenuto
 *
 * **Perché codegen invece di runtime read**:
 *
 * Il `consulente` viene importato sia da Next.js (App Router, Server
 * Components) sia da tsx (script manuali in `scripts/`). Con
 * `readFileSync(join(__dirname, "..", "prompts", "consulente.md"))`
 * a runtime:
 *   - Next 15 bundla `consulente.ts` dentro `.next/server/chunks/`, dove
 *     `__dirname` non punta più a `packages/agents/src/`; il file .md
 *     non viene copiato. Errore ENOENT alla prima richiesta.
 *   - un deploy che sposta il bundle senza `packages/` accanto non
 *     avrebbe comunque il .md a portata di path.
 *   - risolvere con `process.cwd()` sposta il problema di una cartella,
 *     non lo toglie.
 *
 * Codegen risolve alla radice: il contenuto del prompt diventa una
 * costante TypeScript importata come qualunque altra costante, il
 * bundler la inlinea, a runtime non si legge nulla dal filesystem.
 * Vale sia per il webpack di Next sia per tsx (che esegue direttamente
 * il .ts).
 *
 * `PROMPT_VERSION` è calcolato QUI, sulla stessa `md` che viene
 * inlineata: non può divergere da quella runtime. Il valore finisce
 * nella chiave di `pubblico.consiglio_cache` — se cambia il prompt,
 * cambia l'hash, la cache si invalida da sola.
 *
 * Il generato è in `.gitignore`. Va rigenerato con
 *   docker compose run --rm node pnpm --filter @checaldo/agents codegen-prompt
 * o automaticamente dagli hook `predev`/`prebuild`/`pretypecheck`.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";

// Loop su tutti i prompts/*.md: ogni prompt diventa un
// `<nome>-prompt.generated.ts` in src/ con la sua costante
// `PROMPT_MARKDOWN` + `PROMPT_VERSION`. Aggiungere un nuovo prompt
// = aggiungere un .md in `prompts/`, nessuna modifica qui.
const PROMPTS_DIR = join(__dirname, "..", "prompts");
const SRC_DIR = join(__dirname, "..", "src");

const files = readdirSync(PROMPTS_DIR).filter((f) => f.endsWith(".md"));
if (files.length === 0) {
  process.stderr.write("[codegen-prompt] nessun .md in prompts/\n");
  process.exit(1);
}

for (const f of files) {
  const nome = f.replace(/\.md$/, ""); // "consulente", "citta"
  const md = readFileSync(join(PROMPTS_DIR, f), "utf8");
  // SHA-256 primi 8 char sul contenuto ESATTO che verrà inlineato.
  // Nessuna trasformazione fra hash e stringa (no trim, no normalize
  // line endings): quello che c'è in `md` è quello che entra in
  // PROMPT_MARKDOWN e quello su cui si calcola PROMPT_VERSION.
  const ver = createHash("sha256").update(md).digest("hex").slice(0, 8);
  const dst = join(SRC_DIR, `${nome}-prompt.generated.ts`);
  const content =
    `// AUTOGENERATED — non modificare a mano.\n` +
    `// Rigenerato con:\n` +
    `//   docker compose run --rm node pnpm --filter @checaldo/agents codegen-prompt\n` +
    `// Sorgente: packages/agents/prompts/${f}\n` +
    `// SPDX-License-Identifier: AGPL-3.0-or-later\n` +
    `\n` +
    `/* eslint-disable */\n` +
    `export const PROMPT_MARKDOWN: string = ${JSON.stringify(md)};\n` +
    `export const PROMPT_VERSION: string = ${JSON.stringify(ver)};\n`;
  writeFileSync(dst, content, "utf8");
  process.stderr.write(
    `[codegen-prompt] ${nome}: version=${ver}, ${md.length} char → ${dst}\n`,
  );
}
